version: "3.9"
services:
  signaling:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
  turn:
    image: "coturn/coturn:alpine"
    command: --lt-cred-mech --user roboy:4dE5?3sgPb0fOrw5Vh --min-port=49160 --max-port=49200
    network_mode: "host"
    ports:
      ## STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      - "80:80"
      - "80:80/udp"
      ## STUN/TURN SSL
      - "5349:5349"
      - "5349:5349/udp"
      - "5350:5350"
      - "5350:5350/udp"
      - "443:443"
      - "443:443/udp"
      # Relay Ports
      # - "49152-65535:49152-65535"
      # - "49152-65535:49152-65535/udp"
    restart: unless-stopped
